#!/usr/bin/env bash
# install Nginx on a remote server

declare -r config_file='/etc/nginx/sites-available/default'
declare -r listen_pattern='s/^(\s*listen\s+)[0-9]+(.*;)$/\180\2/'

apt-get update
apt-get --yes install 'nginx'
sed --in-place --regexp-extended "$listen_pattern" "$config_file"
echo 'Holberton School' > '/usr/share/nginx/html/index.html'
service nginx reload
service nginx restart
