#!/usr/bin/env bash
# Handle some signals and store a PID in a file

handle_int () {
	echo "Y U no love me?!"
}
handle_term () {
	echo "I hate the kill command"
	rm /var/run/holbertonscript.pid
	exit
}
handle_quit () {
	rm /var/run/holbertonscript.pid
	exit
}

trap handle_int SIGINT
trap handle_term SIGTERM
trap handle_quit SIGQUIT

echo "$$" > /var/run/holbertonscript.pid
while true; do
	echo "To infinity and beyond"
	sleep 2
done
