#!/usr/bin/env bash
# Print all possible times in 12-hour time

declare -i hour=0
declare -i minute

while (( hour < 13 )); do
	echo "Hour: $hour"
	minute=1
	while (( minute < 60 )); do
		echo "$minute"
		(( minute++ ))
	done
	(( hour++ ))
done
