#!/usr/bin/env bash
# Print information about a file using bash tests

if [[ ! -a "holbertonschool" ]]; then
	echo "holbertonschool file does not exist"
else
	echo "holbertonschool file exists"
	if [[ -s "holbertonschool" ]]; then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [[ -f "holbertonschool" ]]; then
		echo "holbertonschool is a regular file"
	fi
fi
